import { normalizeStudyTruthSnapshot, validateStudyTruthSnapshot, type StudyTruthSnapshot } from "./study-truth-layer.js";

export const STUDY_CURRICULUM_PILOT_VERSION = "study-curriculum-pilot-2026.1";

export const STUDY_CURRICULUM_PILOT_SOURCES = {
  singaporeAdditionalMathematics: "https://isomer-user-content.by.gov.sg/334/f4aaac1d-0d7f-492b-88d9-43e392418490/4049_y26_sy.pdf",
  singaporePhysics: "https://isomer-user-content.by.gov.sg/334/42ee79d0-bb13-43f5-94ab-629729f88aa0/6091_y26_sy.pdf",
  jeeMain: "https://cdnbbsr.s3waas.gov.in/s3f8e59f4b2fe7c5705bf878bbd494ccdf/uploads/2025/10/202510311323551056.pdf",
} as const;

/**
 * Small, auditable curriculum seed used to prove cross-curriculum reasoning.
 * Canonical concept names/descriptions and prerequisite edges are Quantora
 * normalization; official syllabus membership is represented only by mappings.
 * No copied question-bank or textbook prose is stored here.
 */
export function buildStudyCurriculumPilot2026(): StudyTruthSnapshot {
  const snapshot = normalizeStudyTruthSnapshot({
    version: STUDY_CURRICULUM_PILOT_VERSION,
    concepts: [
      {
        canonicalId: "math.trigonometry.functions",
        contentVersion: "2026-pilot-1",
        subject: "mathematics",
        label: "Trigonometric functions",
        description: "Interpret and use trigonometric functions across angles and representations.",
        status: "active",
        provenance: "quantora_authored",
        confidence: 0.98,
      },
      {
        canonicalId: "math.trigonometry.identities",
        contentVersion: "2026-pilot-1",
        subject: "mathematics",
        label: "Trigonometric identities",
        description: "Recognise, simplify and apply standard relationships between trigonometric functions.",
        status: "active",
        provenance: "quantora_authored",
        confidence: 0.98,
      },
      {
        canonicalId: "math.vector.scalar-vector",
        contentVersion: "2026-pilot-1",
        subject: "mathematics",
        label: "Scalar and vector quantities",
        description: "Distinguish quantities described only by magnitude from those requiring magnitude and direction.",
        status: "active",
        provenance: "quantora_authored",
        confidence: 0.98,
      },
      {
        canonicalId: "math.vector.resultant",
        contentVersion: "2026-pilot-1",
        subject: "mathematics",
        label: "Vector addition and resultants",
        description: "Combine vectors and determine a resultant representation.",
        status: "active",
        provenance: "quantora_authored",
        confidence: 0.98,
      },
      {
        canonicalId: "math.vector.components",
        contentVersion: "2026-pilot-1",
        subject: "mathematics",
        label: "Vector components",
        description: "Resolve and interpret vectors through coordinate components in two or more dimensions.",
        status: "active",
        provenance: "quantora_authored",
        confidence: 0.98,
      },
      {
        canonicalId: "physics.kinematics.speed-velocity-acceleration",
        contentVersion: "2026-pilot-1",
        subject: "physics",
        label: "Speed, velocity and acceleration",
        description: "Interpret and relate core kinematic rates of motion.",
        status: "active",
        provenance: "quantora_authored",
        confidence: 0.98,
      },
      {
        canonicalId: "physics.kinematics.motion-graphs",
        contentVersion: "2026-pilot-1",
        subject: "physics",
        label: "Motion graphs",
        description: "Interpret displacement-time and velocity-time representations of motion.",
        status: "active",
        provenance: "quantora_authored",
        confidence: 0.98,
      },
      {
        canonicalId: "physics.kinematics.motion-in-plane",
        contentVersion: "2026-pilot-1",
        subject: "physics",
        label: "Motion in a plane",
        description: "Analyse motion with more than one spatial component.",
        status: "active",
        provenance: "quantora_authored",
        confidence: 0.96,
      },
      {
        canonicalId: "physics.kinematics.projectile-motion",
        contentVersion: "2026-pilot-1",
        subject: "physics",
        label: "Projectile motion",
        description: "Apply two-dimensional kinematics to projectile trajectories.",
        status: "active",
        provenance: "quantora_authored",
        confidence: 0.96,
      },
    ],
    edges: [
      {
        sourceConceptId: "math.vector.scalar-vector",
        targetConceptId: "math.vector.resultant",
        relation: "prerequisite_of",
        confidence: 0.95,
        provenance: "derived",
        sourceRef: "quantora:study-pilot-2026:dependency-review",
      },
      {
        sourceConceptId: "math.trigonometry.functions",
        targetConceptId: "math.vector.components",
        relation: "prerequisite_of",
        confidence: 0.9,
        provenance: "derived",
        sourceRef: "quantora:study-pilot-2026:dependency-review",
      },
      {
        sourceConceptId: "math.vector.scalar-vector",
        targetConceptId: "math.vector.components",
        relation: "prerequisite_of",
        confidence: 0.95,
        provenance: "derived",
        sourceRef: "quantora:study-pilot-2026:dependency-review",
      },
      {
        sourceConceptId: "math.vector.components",
        targetConceptId: "physics.kinematics.motion-in-plane",
        relation: "prerequisite_of",
        confidence: 0.95,
        provenance: "derived",
        sourceRef: "quantora:study-pilot-2026:dependency-review",
      },
      {
        sourceConceptId: "physics.kinematics.speed-velocity-acceleration",
        targetConceptId: "physics.kinematics.motion-in-plane",
        relation: "prerequisite_of",
        confidence: 0.95,
        provenance: "derived",
        sourceRef: "quantora:study-pilot-2026:dependency-review",
      },
      {
        sourceConceptId: "physics.kinematics.motion-in-plane",
        targetConceptId: "physics.kinematics.projectile-motion",
        relation: "prerequisite_of",
        confidence: 0.98,
        provenance: "derived",
        sourceRef: "quantora:study-pilot-2026:dependency-review",
      },
      {
        sourceConceptId: "physics.kinematics.motion-graphs",
        targetConceptId: "physics.kinematics.motion-in-plane",
        relation: "supports_transfer_to",
        confidence: 0.8,
        provenance: "derived",
        sourceRef: "quantora:study-pilot-2026:dependency-review",
      },
    ],
    curricula: [
      {
        id: "sg.seab.olevel.additional-mathematics.4049",
        jurisdiction: "singapore",
        authority: "Singapore Examinations and Assessment Board",
        name: "GCE O-Level Additional Mathematics (4049)",
        version: "2026",
        status: "active",
        sourceRef: STUDY_CURRICULUM_PILOT_SOURCES.singaporeAdditionalMathematics,
      },
      {
        id: "sg.seab.olevel.physics.6091",
        jurisdiction: "singapore",
        authority: "Singapore Examinations and Assessment Board",
        name: "GCE O-Level Physics (6091)",
        version: "2026",
        status: "active",
        sourceRef: STUDY_CURRICULUM_PILOT_SOURCES.singaporePhysics,
      },
      {
        id: "in.nta.jeemain.paper1",
        jurisdiction: "india",
        authority: "National Testing Agency",
        name: "JEE Main Paper 1 (B.E./B.Tech.)",
        version: "2026",
        status: "active",
        sourceRef: STUDY_CURRICULUM_PILOT_SOURCES.jeeMain,
      },
    ],
    mappings: [
      {
        curriculumId: "sg.seab.olevel.additional-mathematics.4049",
        conceptId: "math.trigonometry.functions",
        objectiveCode: "G1",
        stage: "O-Level Additional Mathematics",
        depth: 0.5,
        examWeight: null,
        confidence: 1,
        sourceRef: `${STUDY_CURRICULUM_PILOT_SOURCES.singaporeAdditionalMathematics}#page=7`,
      },
      {
        curriculumId: "sg.seab.olevel.additional-mathematics.4049",
        conceptId: "math.trigonometry.identities",
        objectiveCode: "G1",
        stage: "O-Level Additional Mathematics",
        depth: 0.5,
        examWeight: null,
        confidence: 1,
        sourceRef: `${STUDY_CURRICULUM_PILOT_SOURCES.singaporeAdditionalMathematics}#page=7`,
      },
      {
        curriculumId: "sg.seab.olevel.physics.6091",
        conceptId: "math.vector.scalar-vector",
        objectiveCode: "1(f)",
        stage: "O-Level Physics",
        depth: 0.5,
        examWeight: null,
        confidence: 1,
        sourceRef: `${STUDY_CURRICULUM_PILOT_SOURCES.singaporePhysics}#page=10`,
      },
      {
        curriculumId: "sg.seab.olevel.physics.6091",
        conceptId: "math.vector.resultant",
        objectiveCode: "1(g)",
        stage: "O-Level Physics",
        depth: 0.5,
        examWeight: null,
        confidence: 1,
        sourceRef: `${STUDY_CURRICULUM_PILOT_SOURCES.singaporePhysics}#page=10`,
      },
      {
        curriculumId: "sg.seab.olevel.physics.6091",
        conceptId: "physics.kinematics.speed-velocity-acceleration",
        objectiveCode: "2(a-d)",
        stage: "O-Level Physics",
        depth: 0.5,
        examWeight: null,
        confidence: 1,
        sourceRef: `${STUDY_CURRICULUM_PILOT_SOURCES.singaporePhysics}#page=11`,
      },
      {
        curriculumId: "sg.seab.olevel.physics.6091",
        conceptId: "physics.kinematics.motion-graphs",
        objectiveCode: "2(e-h)",
        stage: "O-Level Physics",
        depth: 0.5,
        examWeight: null,
        confidence: 1,
        sourceRef: `${STUDY_CURRICULUM_PILOT_SOURCES.singaporePhysics}#page=11`,
      },
      {
        curriculumId: "in.nta.jeemain.paper1",
        conceptId: "math.trigonometry.functions",
        objectiveCode: "Mathematics Unit 14",
        stage: "JEE Main Paper 1",
        depth: 0.5,
        examWeight: null,
        confidence: 1,
        sourceRef: `${STUDY_CURRICULUM_PILOT_SOURCES.jeeMain}#page=2`,
      },
      {
        curriculumId: "in.nta.jeemain.paper1",
        conceptId: "math.trigonometry.identities",
        objectiveCode: "Mathematics Unit 14",
        stage: "JEE Main Paper 1",
        depth: 0.5,
        examWeight: null,
        confidence: 1,
        sourceRef: `${STUDY_CURRICULUM_PILOT_SOURCES.jeeMain}#page=2`,
      },
      {
        curriculumId: "in.nta.jeemain.paper1",
        conceptId: "math.vector.scalar-vector",
        objectiveCode: "Mathematics Unit 12",
        stage: "JEE Main Paper 1",
        depth: 0.5,
        examWeight: null,
        confidence: 1,
        sourceRef: `${STUDY_CURRICULUM_PILOT_SOURCES.jeeMain}#page=2`,
      },
      {
        curriculumId: "in.nta.jeemain.paper1",
        conceptId: "math.vector.resultant",
        objectiveCode: "Mathematics Unit 12",
        stage: "JEE Main Paper 1",
        depth: 0.5,
        examWeight: null,
        confidence: 0.9,
        sourceRef: `${STUDY_CURRICULUM_PILOT_SOURCES.jeeMain}#page=2`,
      },
      {
        curriculumId: "in.nta.jeemain.paper1",
        conceptId: "math.vector.components",
        objectiveCode: "Mathematics Unit 12",
        stage: "JEE Main Paper 1",
        depth: 0.5,
        examWeight: null,
        confidence: 1,
        sourceRef: `${STUDY_CURRICULUM_PILOT_SOURCES.jeeMain}#page=2`,
      },
      {
        curriculumId: "in.nta.jeemain.paper1",
        conceptId: "physics.kinematics.speed-velocity-acceleration",
        objectiveCode: "Physics Unit 2",
        stage: "JEE Main Paper 1",
        depth: 0.5,
        examWeight: null,
        confidence: 1,
        sourceRef: `${STUDY_CURRICULUM_PILOT_SOURCES.jeeMain}#page=3`,
      },
      {
        curriculumId: "in.nta.jeemain.paper1",
        conceptId: "physics.kinematics.motion-in-plane",
        objectiveCode: "Physics Unit 2",
        stage: "JEE Main Paper 1",
        depth: 0.5,
        examWeight: null,
        confidence: 1,
        sourceRef: `${STUDY_CURRICULUM_PILOT_SOURCES.jeeMain}#page=3`,
      },
      {
        curriculumId: "in.nta.jeemain.paper1",
        conceptId: "physics.kinematics.projectile-motion",
        objectiveCode: "Physics Unit 2",
        stage: "JEE Main Paper 1",
        depth: 0.5,
        examWeight: null,
        confidence: 1,
        sourceRef: `${STUDY_CURRICULUM_PILOT_SOURCES.jeeMain}#page=3`,
      },
    ],
  });

  const validation = validateStudyTruthSnapshot(snapshot);
  if (!validation.valid) {
    throw new Error(`Invalid Study curriculum pilot: ${validation.issues.join("|")}`);
  }
  return snapshot;
}
