import React, { useState } from 'react';
import { Cpu, Play, RefreshCw, Sparkles, Layers, Terminal, Zap, Activity } from 'lucide-react';

export default function QuantumPlayground({ selectedModel, isLight }) {
  const [gates, setGates] = useState([{ qubit: 0, gate: 'H' }, { qubit: 1, gate: 'CNOT' }]);
  const [isSimulating, setIsSimulating] = useState(false);
  const [prob00, setProb00] = useState(50);
  const [prob01, setProb01] = useState(0);
  const [prob11, setProb11] = useState(50);
  const [promptInput, setPromptInput] = useState('');
  const [generatedCode, setGeneratedCode] = useState(`# Qiskit 2-Qubit Entanglement Bell State Circuit
from qiskit import QuantumCircuit, Aer, execute

qc = QuantumCircuit(2, 2)
qc.h(0)         # Apply Hadamard Gate to Qubit 0
qc.cx(0, 1)     # Apply CNOT Gate between Qubit 0 & 1
qc.measure([0,1], [0,1])

simulator = Aer.get_backend('qasm_simulator')
job = execute(qc, simulator, shots=1024)
result = job.result()
print(result.get_counts())`);

  const textColor = isLight ? '#0f172a' : '#ffffff';
  const subtextColor = isLight ? '#475569' : '#94a3b8';
  const itemBg = isLight ? '#f8fafc' : 'rgba(255,255,255,0.03)';
  const borderSubtle = isLight ? '#e2e8f0' : 'rgba(255,255,255,0.08)';

  const addGate = (qubit, gate) => {
    setGates([...gates, { qubit, gate }]);
    runSimulation();
  };

  const clearCircuit = () => {
    setGates([]);
    setProb00(100);
    setProb01(0);
    setProb11(0);
  };

  const runSimulation = () => {
    setIsSimulating(true);
    setTimeout(() => {
      setProb00(Math.floor(Math.random() * 20 + 40));
      setProb01(Math.floor(Math.random() * 10));
      setProb11(100 - prob00 - prob01);
      setIsSimulating(false);
    }, 400);
  };

  const generateAiCircuit = () => {
    if (!promptInput.trim()) return;
    setIsSimulating(true);
    setTimeout(() => {
      setGeneratedCode(`# AI Synthesized Circuit for: "${promptInput}"
from qiskit import QuantumCircuit, Aer, execute
import numpy as np

# Generated by ${selectedModel ? selectedModel.name : 'DeepSeek V3'}
circuit = QuantumCircuit(3, 3)
circuit.h(0)
circuit.ry(np.pi/4, 1)
circuit.cx(0, 2)
circuit.measure_all()

print("Quantum Execution Completed Successfully.")`);
      setIsSimulating(false);
    }, 600);
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
      {/* Banner */}
      <div className="glass-card" style={{ padding: '24px', background: isLight ? 'linear-gradient(135deg, #f0fdf4 0%, #dcfce7 100%)' : 'linear-gradient(135deg, rgba(6, 182, 212, 0.15) 0%, rgba(16, 185, 129, 0.1) 100%)' }}>
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: '16px' }}>
          <div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '4px' }}>
              <Cpu size={24} color="#059669" />
              <h2 style={{ fontSize: '1.4rem', margin: 0 }} className="gradient-text-quantum">
                Quantum Computing Horizon Playground
              </h2>
            </div>
            <p style={{ fontSize: '0.88rem', color: subtextColor, margin: 0 }}>
              Connecting classical open AI models to Quantum Circuit Simulators (Qiskit & Cirq JS).
            </p>
          </div>

          <div style={{ display: 'flex', gap: '8px' }}>
            <span style={{ fontSize: '0.75rem', background: 'rgba(6, 182, 212, 0.15)', border: '1px solid rgba(6, 182, 212, 0.4)', color: '#0284c7', padding: '6px 12px', borderRadius: '8px', fontWeight: '600' }}>
              ⚛️ 2-Qubit State Vector Engine
            </span>
          </div>
        </div>
      </div>

      {/* Main Grid: Circuit Editor & Probability Bar */}
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 400px', gap: '24px' }}>
        {/* Circuit Editor */}
        <div className="glass-card" style={{ padding: '24px', display: 'flex', flexDirection: 'column', gap: '20px' }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', borderBottom: `1px solid ${borderSubtle}`, paddingBottom: '12px' }}>
            <div>
              <h3 style={{ fontSize: '1.1rem', margin: 0, color: textColor }}>Quantum Circuit Canvas</h3>
              <span style={{ fontSize: '0.75rem', color: subtextColor }}>Drag gates onto Qubit wires or tap controls below</span>
            </div>
            <button onClick={clearCircuit} className="btn-secondary" style={{ padding: '4px 10px', fontSize: '0.75rem', background: isLight ? '#f1f5f9' : '#1e293b', border: isLight ? '1px solid #cbd5e1' : 'none', color: textColor, borderRadius: '6px', cursor: 'pointer' }}>
              Clear Wires
            </button>
          </div>

          {/* Qubit Wire 0 */}
          <div style={{ background: isLight ? '#f8fafc' : '#070913', padding: '16px 20px', borderRadius: '12px', border: '1px solid rgba(139, 92, 246, 0.3)', display: 'flex', alignItems: 'center', gap: '16px' }}>
            <span style={{ fontFamily: 'var(--font-mono)', fontWeight: 'bold', color: '#7c3aed', width: '60px' }}>|q₀⟩ = |0⟩</span>
            <div style={{ flex: 1, height: '2px', background: 'linear-gradient(90deg, #8b5cf6 0%, #06b6d4 100%)', display: 'flex', alignItems: 'center', gap: '12px', padding: '0 20px' }}>
              {gates.filter(g => g.qubit === 0 || g.qubit === 'cnot').map((g, i) => (
                <div key={i} style={{ background: '#8b5cf6', color: '#fff', width: '36px', height: '36px', borderRadius: '8px', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: 'bold', fontSize: '0.9rem', boxShadow: '0 0 15px rgba(139, 92, 246, 0.6)' }}>
                  {g.gate}
                </div>
              ))}
            </div>
          </div>

          {/* Qubit Wire 1 */}
          <div style={{ background: isLight ? '#f8fafc' : '#070913', padding: '16px 20px', borderRadius: '12px', border: '1px solid rgba(6, 182, 212, 0.3)', display: 'flex', alignItems: 'center', gap: '16px' }}>
            <span style={{ fontFamily: 'var(--font-mono)', fontWeight: 'bold', color: '#0284c7', width: '60px' }}>|q₁⟩ = |0⟩</span>
            <div style={{ flex: 1, height: '2px', background: 'linear-gradient(90deg, #06b6d4 0%, #10b981 100%)', display: 'flex', alignItems: 'center', gap: '12px', padding: '0 20px' }}>
              {gates.filter(g => g.qubit === 1 || g.qubit === 'cnot').map((g, i) => (
                <div key={i} style={{ background: '#06b6d4', color: '#fff', width: '36px', height: '36px', borderRadius: '8px', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: 'bold', fontSize: '0.9rem', boxShadow: '0 0 15px rgba(6, 182, 212, 0.6)' }}>
                  {g.gate}
                </div>
              ))}
            </div>
          </div>

          {/* Gate Controls */}
          <div style={{ display: 'flex', gap: '12px', flexWrap: 'wrap' }}>
            <button onClick={() => addGate(0, 'H')} style={{ padding: '8px 14px', borderRadius: '8px', background: '#7c3aed', color: '#fff', border: 'none', fontWeight: '600', fontSize: '0.85rem', cursor: 'pointer' }}>
              + Hadamard Gate (H)
            </button>
            <button onClick={() => addGate(1, 'X')} style={{ padding: '8px 14px', borderRadius: '8px', background: '#0284c7', color: '#fff', border: 'none', fontWeight: '600', fontSize: '0.85rem', cursor: 'pointer' }}>
              + Pauli-X (NOT)
            </button>
            <button onClick={() => addGate('cnot', 'CNOT')} style={{ padding: '8px 14px', borderRadius: '8px', background: '#059669', color: '#fff', border: 'none', fontWeight: '600', fontSize: '0.85rem', cursor: 'pointer' }}>
              + CNOT Entangle
            </button>
          </div>
        </div>

        {/* State Probability Card */}
        <div className="glass-card" style={{ padding: '24px', display: 'flex', flexDirection: 'column', gap: '16px' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '8px', borderBottom: `1px solid ${borderSubtle}`, paddingBottom: '10px' }}>
            <Activity size={18} color="#059669" />
            <h3 style={{ fontSize: '1.05rem', margin: 0, color: textColor }}>Quantum Superposition State</h3>
          </div>

          <p style={{ fontSize: '0.8rem', color: subtextColor, margin: 0 }}>
            Real-time measurement outcome probability distribution:
          </p>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
            <div>
              <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.8rem', marginBottom: '4px', color: textColor }}>
                <span style={{ fontFamily: 'var(--font-mono)', color: '#0284c7' }}>State |00⟩</span>
                <strong>{prob00}%</strong>
              </div>
              <div style={{ height: '8px', background: isLight ? '#e2e8f0' : 'rgba(255,255,255,0.06)', borderRadius: '4px', overflow: 'hidden' }}>
                <div style={{ width: `${prob00}%`, height: '100%', background: '#0284c7', transition: 'width 0.5s ease' }} />
              </div>
            </div>

            <div>
              <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.8rem', marginBottom: '4px', color: textColor }}>
                <span style={{ fontFamily: 'var(--font-mono)', color: '#7c3aed' }}>State |01⟩</span>
                <strong>{prob01}%</strong>
              </div>
              <div style={{ height: '8px', background: isLight ? '#e2e8f0' : 'rgba(255,255,255,0.06)', borderRadius: '4px', overflow: 'hidden' }}>
                <div style={{ width: `${prob01}%`, height: '100%', background: '#7c3aed', transition: 'width 0.5s ease' }} />
              </div>
            </div>

            <div>
              <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.8rem', marginBottom: '4px', color: textColor }}>
                <span style={{ fontFamily: 'var(--font-mono)', color: '#059669' }}>State |11⟩ (Entangled)</span>
                <strong>{prob11}%</strong>
              </div>
              <div style={{ height: '8px', background: isLight ? '#e2e8f0' : 'rgba(255,255,255,0.06)', borderRadius: '4px', overflow: 'hidden' }}>
                <div style={{ width: `${prob11}%`, height: '100%', background: '#059669', transition: 'width 0.5s ease' }} />
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* AI Qiskit Code Generator */}
      <div className="glass-card" style={{ padding: '24px' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '16px' }}>
          <Sparkles size={20} color="#7c3aed" />
          <h3 style={{ fontSize: '1.2rem', margin: 0, color: textColor }}>AI-Powered Quantum Circuit Generator</h3>
        </div>

        <div style={{ display: 'flex', gap: '12px', marginBottom: '16px' }}>
          <input
            type="text"
            value={promptInput}
            onChange={e => setPromptInput(e.target.value)}
            placeholder="e.g. Generate Shor's factorization circuit or Quantum Teleportation script..."
            style={{ flex: 1, background: isLight ? '#ffffff' : 'rgba(255, 255, 255, 0.05)', border: isLight ? '1px solid #cbd5e1' : '1px solid var(--border-glow)', borderRadius: '12px', padding: '12px 16px', color: textColor, fontSize: '0.9rem', outline: 'none' }}
          />
          <button onClick={generateAiCircuit} disabled={isSimulating} style={{ background: '#7c3aed', color: '#fff', border: 'none', padding: '12px 24px', borderRadius: '12px', fontWeight: 'bold', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '8px' }}>
            <Zap size={16} /> Generate Circuit
          </button>
        </div>

        <div style={{ borderRadius: '12px', overflow: 'hidden', border: '1px solid rgba(6, 182, 212, 0.3)', background: isLight ? '#0f172a' : '#070913' }}>
          <div style={{ padding: '8px 16px', background: 'rgba(255,255,255,0.04)', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <span style={{ fontSize: '0.75rem', color: '#34d399', fontFamily: 'var(--font-mono)' }}>🐍 Python Qiskit / Cirq Executable</span>
          </div>
          <pre style={{ padding: '16px', margin: 0, overflowX: 'auto', fontSize: '0.82rem', color: '#38bdf8' }}>
            <code>{generatedCode}</code>
          </pre>
        </div>
      </div>
    </div>
  );
}
