import React, { useState, useMemo } from 'react';
import { Cpu, Play, RefreshCw, Sparkles, Layers, Terminal, Zap, Activity } from 'lucide-react';
import { runCircuit, runCircuitTo, sample } from '../lib/quantum/statevector';
import BlochSphere from './BlochSphere';

const NUM_QUBITS = 2;

export default function QuantumPlayground({ selectedModel, isLight }) {
  /*
   * The circuit is the single source of truth, and the state is derived from
   * it by actually simulating. Nothing here is stored as a probability that
   * could drift out of step with the gates on screen.
   *
   * Previously these bars came from Math.random(), so the panel could show a
   * Bell pair with a non-zero chance of |01> — a state that is physically
   * impossible. Anyone checking their homework against it was being taught
   * incorrect physics.
   */
  const [circuit, setCircuit] = useState([
    { gate: 'H', target: 0 },
    { gate: 'CNOT', control: 0, target: 1 },
  ]);
  const [shots, setShots] = useState(1024);
  const [measured, setMeasured] = useState(null);
  const [isSimulating, setIsSimulating] = useState(false);
  const [promptInput, setPromptInput] = useState('');

  /*
   * Step position. `null` means "show the finished circuit"; a number means the
   * user is walking through it. The whole panel reads from whatever state this
   * resolves to, so the bars, the spheres and the totals can never disagree
   * about which moment they are describing.
   */
  const [step, setStep] = useState(null);
  const atStep = step === null ? circuit.length : Math.min(step, circuit.length);

  /* Exact amplitudes for the moment currently being shown. */
  const state = useMemo(() => runCircuitTo(NUM_QUBITS, circuit, atStep), [circuit, atStep]);
  const exact = useMemo(() => Array.from(state.probabilities()), [state]);
  const labels = useMemo(
    () => Array.from({ length: 1 << NUM_QUBITS }, (_, i) => i.toString(2).padStart(NUM_QUBITS, '0')),
    []
  );
  /*
   * Exported Qiskit, generated from the circuit actually on screen.
   *
   * The previous sample was hardcoded AND broken: it imported `Aer` and
   * `execute` from `qiskit`, both removed in Qiskit 1.0. Anyone who copied it
   * hit an ImportError immediately. Modern Qiskit uses the Sampler primitives
   * from qiskit_aer, which is what this emits.
   */
  const generatedCode = useMemo(() => {
    const lines = circuit.map((g) => {
      if (g.gate === 'CNOT' || g.gate === 'CX') return `qc.cx(${g.control}, ${g.target})`;
      if (g.gate === 'CZ') return `qc.cz(${g.control}, ${g.target})`;
      if (g.gate === 'SWAP') return `qc.swap(${g.control}, ${g.target})`;
      if (['RX', 'RY', 'RZ'].includes(g.gate)) {
        return `qc.${g.gate.toLowerCase()}(${(g.angle ?? Math.PI / 2).toFixed(6)}, ${g.target})`;
      }
      return `qc.${g.gate.toLowerCase()}(${g.target})`;
    });

    return [
      '# Generated by Quantora — runs on Qiskit 1.0+',
      'from qiskit import QuantumCircuit, transpile',
      'from qiskit_aer import AerSimulator',
      '',
      `qc = QuantumCircuit(${NUM_QUBITS}, ${NUM_QUBITS})`,
      ...(lines.length ? lines : ['# (no gates yet — the register stays in |0…0>)']),
      'qc.measure_all()',
      '',
      'sim = AerSimulator()',
      'result = sim.run(transpile(qc, sim), shots=' + shots + ').result()',
      'print(result.get_counts())',
    ].join('\n');
  }, [circuit, shots]);

  const textColor = isLight ? '#0f172a' : '#ffffff';
  const subtextColor = isLight ? '#475569' : '#94a3b8';
  const itemBg = isLight ? '#f8fafc' : 'rgba(255,255,255,0.03)';
  const borderSubtle = isLight ? '#e2e8f0' : 'rgba(255,255,255,0.08)';

  const addGate = (gateStep) => {
    setCircuit((prev) => [...prev, gateStep]);
    setMeasured(null);   // the old shots describe a circuit that no longer exists
    setStep(null);       // jump back to the end so the new gate is visible
  };

  const clearCircuit = () => {
    setCircuit([]);
    setMeasured(null);
    setStep(null);
  };

  const undoGate = () => {
    setCircuit((prev) => prev.slice(0, -1));
    setMeasured(null);
    setStep(null);
  };

  /*
   * Measurement is a separate act from knowing the state.
   *
   * A real device never hands you a distribution — it returns one outcome per
   * shot, and the distribution only emerges from repetition. Sampling here,
   * and showing the result beside the exact curve, is what makes that
   * difference visible rather than a sentence in a textbook.
   */
  const runMeasurement = () => {
    setIsSimulating(true);
    setTimeout(() => {
      const counts = sample(state, shots);
      setMeasured(Array.from(counts));
      setIsSimulating(false);
    }, 260);
  };

  /*
   * Turn a phrase into a circuit that is actually built and actually run.
   *
   * This used to return a fixed block of Python with the prompt pasted into a
   * comment — it ignored what was asked for and simulated nothing. Recognised
   * patterns now assemble real gates, which flow into the same simulator and
   * the same exported code as anything placed by hand. When the phrase is not
   * understood it says so, rather than inventing a circuit and implying the
   * request was honoured.
   *
   * A language model would widen this considerably; that is a later step. What
   * matters at this stage is that nothing on screen is fabricated.
   */
  const [buildNote, setBuildNote] = useState('');

  const generateAiCircuit = () => {
    const text = promptInput.trim().toLowerCase();
    if (!text) return;

    setIsSimulating(true);
    setTimeout(() => {
      let built = null;
      let note = '';

      if (/(bell|entangl|epr)/.test(text)) {
        built = [{ gate: 'H', target: 0 }, { gate: 'CNOT', control: 0, target: 1 }];
        note = 'Bell pair — the two qubits now always agree, though neither is decided until measured.';
      } else if (/(superposition|coin|equal|uniform)/.test(text)) {
        built = [{ gate: 'H', target: 0 }, { gate: 'H', target: 1 }];
        note = 'Both qubits in superposition — all four outcomes equally likely.';
      } else if (/(flip|not|invert|excite)/.test(text)) {
        built = [{ gate: 'X', target: 0 }];
        note = 'A single bit flip. Qubit 0 is now certainly |1>.';
      } else if (/(interfer|cancel|hadamard twice|undo)/.test(text)) {
        built = [{ gate: 'H', target: 0 }, { gate: 'Z', target: 0 }, { gate: 'H', target: 0 }];
        note = 'Interference: H–Z–H returns a definite answer, and it is the opposite one. Randomness alone could not do this.';
      } else if (/(rotate|angle|partial|bias)/.test(text)) {
        built = [{ gate: 'RY', target: 0, angle: Math.PI / 4 }];
        note = 'A partial rotation — an unequal, but still perfectly defined, superposition.';
      } else {
        note = `No circuit pattern recognised in "${promptInput.trim()}". Try: Bell state, superposition, interference, bit flip, or rotation.`;
      }

      if (built) setCircuit(built);
      setMeasured(null);
      setStep(null);
      setBuildNote(note);
      setIsSimulating(false);
    }, 320);
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
      {/* Banner */}
      <div className="glass-card" style={{ padding: '24px', background: isLight ? 'linear-gradient(135deg, #f0fdf4 0%, #dcfce7 100%)' : 'linear-gradient(135deg, rgba(6, 182, 212, 0.15) 0%, rgba(16, 185, 129, 0.1) 100%)' }}>
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: '16px' }}>
          <div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '4px' }}>
              <Cpu size={24} color="#059669" />
              <h2 style={{ fontSize: '1.4rem', margin: 0 }} className="gradient-text-quantum">
                Quantum Computing Horizon Playground
              </h2>
            </div>
            <p style={{ fontSize: '0.88rem', color: subtextColor, margin: 0 }}>
              An exact state-vector simulator running in your browser. Build a circuit, see the real amplitudes, then measure it.
            </p>
          </div>

          <div style={{ display: 'flex', gap: '8px' }}>
            <span style={{ fontSize: '0.75rem', background: 'rgba(6, 182, 212, 0.15)', border: '1px solid rgba(6, 182, 212, 0.4)', color: '#0284c7', padding: '6px 12px', borderRadius: '8px', fontWeight: '600' }}>
              ⚛️ Exact 2-qubit state vector
            </span>
          </div>
        </div>
      </div>

      {/* Main Grid: Circuit Editor & Probability Bar */}
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 400px', gap: '24px' }}>
        {/* Circuit Editor */}
        <div className="glass-card" style={{ padding: '24px', display: 'flex', flexDirection: 'column', gap: '20px' }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', borderBottom: `1px solid ${borderSubtle}`, paddingBottom: '12px' }}>
            <div>
              <h3 style={{ fontSize: '1.1rem', margin: 0, color: textColor }}>Quantum Circuit Canvas</h3>
              <span style={{ fontSize: '0.75rem', color: subtextColor }}>Drag gates onto Qubit wires or tap controls below</span>
            </div>
            <button onClick={clearCircuit} className="btn-secondary" style={{ padding: '4px 10px', fontSize: '0.75rem', background: isLight ? '#f1f5f9' : '#1e293b', border: isLight ? '1px solid #cbd5e1' : 'none', color: textColor, borderRadius: '6px', cursor: 'pointer' }}>
              Clear Wires
            </button>
          </div>

          {/* Qubit Wire 0 */}
          <div style={{ background: isLight ? '#f8fafc' : '#070913', padding: '16px 20px', borderRadius: '12px', border: '1px solid rgba(139, 92, 246, 0.3)', display: 'flex', alignItems: 'center', gap: '16px' }}>
            <span style={{ fontFamily: 'var(--font-mono)', fontWeight: 'bold', color: '#7c3aed', width: '60px' }}>|q₀⟩ = |0⟩</span>
            <div style={{ flex: 1, height: '2px', background: 'linear-gradient(90deg, #8b5cf6 0%, #06b6d4 100%)', display: 'flex', alignItems: 'center', gap: '12px', padding: '0 20px' }}>
              {circuit.filter(g => g.target === 0 || g.control === 0).map((g, i) => (
                <div key={i} style={{ background: '#8b5cf6', color: '#fff', width: '36px', height: '36px', borderRadius: '8px', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: 'bold', fontSize: '0.9rem', boxShadow: '0 0 15px rgba(139, 92, 246, 0.6)' }}>
                  {g.gate}
                </div>
              ))}
            </div>
          </div>

          {/* Qubit Wire 1 */}
          <div style={{ background: isLight ? '#f8fafc' : '#070913', padding: '16px 20px', borderRadius: '12px', border: '1px solid rgba(6, 182, 212, 0.3)', display: 'flex', alignItems: 'center', gap: '16px' }}>
            <span style={{ fontFamily: 'var(--font-mono)', fontWeight: 'bold', color: '#0284c7', width: '60px' }}>|q₁⟩ = |0⟩</span>
            <div style={{ flex: 1, height: '2px', background: 'linear-gradient(90deg, #06b6d4 0%, #10b981 100%)', display: 'flex', alignItems: 'center', gap: '12px', padding: '0 20px' }}>
              {circuit.filter(g => g.target === 1 || g.control === 1).map((g, i) => (
                <div key={i} style={{ background: '#06b6d4', color: '#fff', width: '36px', height: '36px', borderRadius: '8px', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: 'bold', fontSize: '0.9rem', boxShadow: '0 0 15px rgba(6, 182, 212, 0.6)' }}>
                  {g.gate}
                </div>
              ))}
            </div>
          </div>

          {/* Gate Controls */}
          <div style={{ display: 'flex', gap: '12px', flexWrap: 'wrap' }}>
            <button onClick={() => addGate({ gate: 'H', target: 0 })} style={{ padding: '8px 14px', borderRadius: '8px', background: '#7c3aed', color: '#fff', border: 'none', fontWeight: '600', fontSize: '0.85rem', cursor: 'pointer' }}>
              + Hadamard Gate (H)
            </button>
            <button onClick={() => addGate({ gate: 'X', target: 1 })} style={{ padding: '8px 14px', borderRadius: '8px', background: '#0284c7', color: '#fff', border: 'none', fontWeight: '600', fontSize: '0.85rem', cursor: 'pointer' }}>
              + Pauli-X (NOT)
            </button>
            <button onClick={() => addGate({ gate: 'CNOT', control: 0, target: 1 })} style={{ padding: '8px 14px', borderRadius: '8px', background: '#059669', color: '#fff', border: 'none', fontWeight: '600', fontSize: '0.85rem', cursor: 'pointer' }}>
              + CNOT Entangle
            </button>
          </div>
        </div>

        {/* State Probability Card */}
        <div className="glass-card" style={{ padding: '24px', display: 'flex', flexDirection: 'column', gap: '16px' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '8px', borderBottom: `1px solid ${borderSubtle}`, paddingBottom: '10px' }}>
            <Activity size={18} color="#059669" />
            <h3 style={{ fontSize: '1.05rem', margin: 0, color: textColor }}>Quantum Superposition State</h3>
          </div>

          <p style={{ fontSize: '0.8rem', color: subtextColor, margin: 0 }}>
            Exact probabilities from the state vector. Every outcome is listed, including
            the impossible ones — a zero here is a physical fact, not a rounding artefact.
          </p>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
            {exact.map((prob, i) => {
              const palette = ['#0284c7', '#7c3aed', '#f97316', '#059669'];
              const colour = palette[i % palette.length];
              const measuredShare = measured ? measured[i] / shots : null;
              return (
                <div key={i}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.8rem', marginBottom: '4px', color: textColor }}>
                    <span style={{ fontFamily: 'var(--font-mono)', color: colour }}>|{labels[i]}⟩</span>
                    <span style={{ display: 'flex', gap: '10px', alignItems: 'baseline' }}>
                      <strong>{(prob * 100).toFixed(1)}%</strong>
                      {measuredShare !== null && (
                        <span style={{ fontSize: '0.72rem', color: subtextColor, fontFamily: 'var(--font-mono)' }}>
                          {measured[i]} shots
                        </span>
                      )}
                    </span>
                  </div>

                  {/* Exact probability */}
                  <div style={{ height: '8px', background: isLight ? '#e2e8f0' : 'rgba(255,255,255,0.06)', borderRadius: '4px', overflow: 'hidden' }}>
                    <div style={{ width: `${prob * 100}%`, height: '100%', background: colour, transition: 'width 0.4s ease' }} />
                  </div>

                  {/*
                    * Sampled result underneath, deliberately not smoothed. Seeing it
                    * land near — but not on — the exact bar is the point: that gap is
                    * sampling noise, and it shrinks as the shot count rises.
                    */}
                  {measuredShare !== null && (
                    <div style={{ height: '4px', marginTop: '3px', background: isLight ? '#f1f5f9' : 'rgba(255,255,255,0.03)', borderRadius: '3px', overflow: 'hidden' }}>
                      <div style={{ width: `${measuredShare * 100}%`, height: '100%', background: colour, opacity: 0.45, transition: 'width 0.4s ease' }} />
                    </div>
                  )}
                </div>
              );
            })}
          </div>

          {/*
            * Bloch spheres, one per qubit.
            *
            * The probability bars above describe the register as a whole. These
            * describe each qubit on its own — and the moment a CNOT lands, both
            * arrows vanish, because neither qubit has an individual state any
            * more. That collapse is entanglement, shown rather than asserted.
            */}
          <div style={{ borderTop: `1px solid ${borderSubtle}`, paddingTop: '16px' }}>
            <div style={{ fontSize: '0.8rem', color: subtextColor, marginBottom: '10px' }}>
              Each qubit on its own:
            </div>
            <div style={{ display: 'flex', gap: '10px', justifyContent: 'space-around', flexWrap: 'wrap' }}>
              {Array.from({ length: NUM_QUBITS }, (_, q) => (
                <BlochSphere key={q} state={state} qubit={q} label={`q${q}`} isLight={isLight} />
              ))}
            </div>
          </div>

          {/*
            * Step-through.
            *
            * The final distribution says where the circuit ended up and nothing
            * about how it got there. Walking the gates one at a time is where
            * the intuition actually forms — you can watch superposition appear,
            * then watch entanglement consume it.
            */}
          {circuit.length > 0 && (
            <div style={{ borderTop: `1px solid ${borderSubtle}`, paddingTop: '14px', display: 'flex', flexDirection: 'column', gap: '8px' }}>
              <label style={{ fontSize: '0.78rem', color: subtextColor, display: 'flex', justifyContent: 'space-between' }}>
                <span>Step through</span>
                <strong style={{ color: textColor, fontFamily: 'var(--font-mono)' }}>
                  {atStep} / {circuit.length}
                </strong>
              </label>
              <input
                type="range" min="0" max={circuit.length} step="1"
                value={atStep}
                onChange={(e) => {
                  const v = Number(e.target.value);
                  setStep(v === circuit.length ? null : v);
                  setMeasured(null);
                }}
                style={{ width: '100%', accentColor: '#7c3aed' }}
              />
              <div style={{ fontSize: '0.72rem', color: subtextColor, minHeight: '17px' }}>
                {atStep === 0
                  ? 'Before any gate — the register sits in |0…0⟩.'
                  : `Just applied: ${circuit[atStep - 1].gate}${
                      circuit[atStep - 1].control !== undefined
                        ? ` (control q${circuit[atStep - 1].control} → target q${circuit[atStep - 1].target})`
                        : ` on q${circuit[atStep - 1].target}`
                    }`}
              </div>
            </div>
          )}

          <div style={{ borderTop: `1px solid ${borderSubtle}`, paddingTop: '14px', display: 'flex', flexDirection: 'column', gap: '10px' }}>
            <label style={{ fontSize: '0.78rem', color: subtextColor, display: 'flex', justifyContent: 'space-between' }}>
              <span>Shots</span>
              <strong style={{ color: textColor, fontFamily: 'var(--font-mono)' }}>{shots}</strong>
            </label>
            <input
              type="range" min="1" max="4096" step="1"
              value={shots}
              onChange={(e) => { setShots(Number(e.target.value)); setMeasured(null); }}
              style={{ width: '100%', accentColor: '#059669' }}
            />
            <button
              onClick={runMeasurement}
              disabled={isSimulating}
              style={{ padding: '10px 14px', borderRadius: '9px', background: '#059669', color: '#fff', border: 'none', fontWeight: 600, fontSize: '0.85rem', cursor: isSimulating ? 'default' : 'pointer', opacity: isSimulating ? 0.7 : 1 }}
            >
              {isSimulating ? 'Measuring…' : `Measure ${shots} times`}
            </button>
            <p style={{ fontSize: '0.72rem', color: subtextColor, margin: 0, lineHeight: 1.5 }}>
              Total probability {(exact.reduce((a, b) => a + b, 0) * 100).toFixed(4)}% — it must always be 100%.
            </p>
          </div>
        </div>
      </div>

      {/* AI Qiskit Code Generator */}
      <div className="glass-card" style={{ padding: '24px' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '16px' }}>
          <Sparkles size={20} color="#7c3aed" />
          <h3 style={{ fontSize: '1.2rem', margin: 0, color: textColor }}>AI-Powered Quantum Circuit Generator</h3>
        </div>

        <div style={{ display: 'flex', gap: '12px', marginBottom: '16px' }}>
          <input
            type="text"
            value={promptInput}
            onChange={e => setPromptInput(e.target.value)}
            placeholder="e.g. Generate Shor's factorization circuit or Quantum Teleportation script..."
            style={{ flex: 1, background: isLight ? '#ffffff' : 'rgba(255, 255, 255, 0.05)', border: isLight ? '1px solid #cbd5e1' : '1px solid var(--border-glow)', borderRadius: '12px', padding: '12px 16px', color: textColor, fontSize: '0.9rem', outline: 'none' }}
          />
          <button onClick={generateAiCircuit} disabled={isSimulating} style={{ background: '#7c3aed', color: '#fff', border: 'none', padding: '12px 24px', borderRadius: '12px', fontWeight: 'bold', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '8px' }}>
            <Zap size={16} /> Generate Circuit
          </button>
          {buildNote && (
            <p style={{ fontSize: '0.78rem', color: subtextColor, margin: '10px 0 0', lineHeight: 1.55, borderLeft: `2px solid ${'#059669'}`, paddingLeft: '10px' }}>
              {buildNote}
            </p>
          )}
        </div>

        <div style={{ borderRadius: '12px', overflow: 'hidden', border: '1px solid rgba(6, 182, 212, 0.3)', background: isLight ? '#0f172a' : '#070913' }}>
          <div style={{ padding: '8px 16px', background: 'rgba(255,255,255,0.04)', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <span style={{ fontSize: '0.75rem', color: '#34d399', fontFamily: 'var(--font-mono)' }}>🐍 Python Qiskit / Cirq Executable</span>
          </div>
          <pre style={{ padding: '16px', margin: 0, overflowX: 'auto', fontSize: '0.82rem', color: '#38bdf8' }}>
            <code>{generatedCode}</code>
          </pre>
        </div>
      </div>
    </div>
  );
}
