create table if not exists public.runtime_governor_events (
  id bigint generated by default as identity primary key,
  lifecycle_id text not null,
  correlation_id text not null,
  lifecycle_state text not null check (lifecycle_state in ('received','planned','executing','validating','recovering','completed','failed')),
  event_at timestamptz not null default now(),
  user_sub text,
  run_id text,
  source text not null check (source in ('chat','qir','delivery','system')),
  provider text,
  model_id text,
  route text,
  tool text,
  workspace_id text,
  retry_count integer not null default 0 check (retry_count >= 0),
  recovery_count integer not null default 0 check (recovery_count >= 0),
  terminal boolean not null default false,
  verified boolean not null default false,
  reason text,
  evidence_ref text,
  created_at timestamptz not null default now()
);

create unique index if not exists runtime_governor_terminal_once_idx
  on public.runtime_governor_events (correlation_id)
  where terminal = true;

create index if not exists runtime_governor_correlation_idx
  on public.runtime_governor_events (correlation_id, event_at, id);

create index if not exists runtime_governor_state_time_idx
  on public.runtime_governor_events (lifecycle_state, event_at desc);

alter table public.runtime_governor_events enable row level security;
revoke all on table public.runtime_governor_events from public, anon, authenticated;
